# config to select component, the format is CONFIG_USE_${component}
set(CONFIG_USE_middleware_fatfs_usb_MCXN947_cm33_core0 true)
set(CONFIG_USE_component_serial_manager_uart_MCXN947_cm33_core0 true)
set(CONFIG_USE_middleware_usb_host_khci_MCXN947_cm33_core0 true)
set(CONFIG_USE_driver_lpuart_MCXN947_cm33_core0 true)
set(CONFIG_USE_middleware_usb_host_ehci_MCXN947_cm33_core0 true)
set(CONFIG_USE_middleware_freertos-kernel_MCXN947_cm33_core0 true)
