# config to select component, the format is CONFIG_USE_${component}
set(CONFIG_USE_middleware_sdmmc_host_usdhc_MCXN947_cm33_core0 true)
set(CONFIG_USE_middleware_sdmmc_host_usdhc_interrupt_MCXN947_cm33_core0 true)
set(CONFIG_USE_driver_lpuart_MCXN947_cm33_core0 true)
